theme:
  name: material
site_name: winsonYe
nav:
  - Home: index.md
  - 开发: 
    # - 前端开发: - software_development/frontend/frontend.md
    - 后端开发: 
      - 面经: software_development/backend/interview_experiences.md
  - 算法题: 
    - 算法基础: algorithm/algorithm_basic.md
    - leetcode刷题笔记: algorithm/leetcode.md
  - About: about.md

